--- 
redis_ambassador: 
  container_name: redis-ambassador
  environment: 
    - "REDIS_PORT_6379_TCP=tcp://162.243.11.216:6379"
  expose: 
    - 6379
  image: svendowideit/ambassador
  ports: 
    - "6379:6379"
